// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || import.meta.env.NEXT_PUBLIC_SUPABASE_URL || "https://wrabcfmvyfzvdpudawvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || "sb_publishable_5CtKIzvsjZ-FSXthGaf_tA_484h8zgF";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const bypass = import.meta.env.VITE_BYPASS_SUPABASE_FUNCTIONS === "true";

export const supabase = createClient<Database>(
  SUPABASE_URL || "https://placeholder.supabase.co",
  SUPABASE_PUBLISHABLE_KEY || "placeholder-key",
  {
    auth: {
      storage: bypass ? {
        getItem: () => null,
        setItem: () => {},
        removeItem: () => {},
      } : localStorage,
      persistSession: !bypass,
      autoRefreshToken: !bypass,
    }
  }
);